name: SnapEnhanceModGen Action

on:
  push:
    paths:
      - 'push-here.md'
      - '**/core.apk'
      - '**/lspatch.jar'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$(echo ${{ steps.setup-java.outputs.java-home }})" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
        shell: bash

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Install pup
        run: |
         wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip -O pup.zip
         unzip pup.zip
         chmod +x pup
         sudo mv pup /usr/local/bin/
        working-directory: . 

      - name: Grant execute permissions to script
        run: chmod +x betascript.sh
        working-directory: .  

      - name: Run APK Download Script
        run: |
         ./betascript.sh  

      - name: Run the command
        run: |
          java -jar lspatch.jar -m "$GITHUB_WORKSPACE/core.apk" -f -l 2 -v snap.apk

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: snap-402-lspatched.apk
          path: ./snap-402-lspatched.apk
          overwrite: true

      - name: Check if the release already exists
        id: check_release
        run: |
          RELEASE_VERSION=v0.0  # Change this to the initial release version
          if curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/tags/$RELEASE_VERSION; then
            echo "Release $RELEASE_VERSION already exists."
            # Increment the release version
            RELEASE_VERSION=$(echo $RELEASE_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./')
          fi
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Create or Update Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: snap-402-lspatched.apk
          tag_name: ${{ env.RELEASE_VERSION }}-Beta  # Append "-Beta" to the tag name
